name: ESPP2 pytest

on: [push]

env:
  ESPP2_VAULT_PATH: "vault.json"

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      # - name: Lint with flake8
      #  run: |
      #    # stop the build if there are Python syntax errors or undefined names
      #    flake8 espp2 --count --select=E9,F63,F7,F82 --show-source --statistics
      #    # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
      #    flake8 espp2 --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Create vault.json
        run: |
          echo '{"EODHD": "${{ secrets.EODHD }}"}' > vault.json
      - name: Test with pytest
        run: |
          pip install -e .
          pytest
